# Generated by Django 2.0.13 on 2019-02-25 02:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('hrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('votecount', django.db.models.manager.Manager()),
            ],
        ),
    ]
